---
title: Litetokens.co
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: https://litetokens.co
theme:
  title: Litetokens
  avatar: XLT.png
  gravatar: 
  description: "## Litetokens - The Best Way to Trade Everything"
  header_text: "## Litetokens - the best way to trade everything."
  footer_text: "© Kedia Corporation\n"
  rss: false
  email_address: 
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: litetokens
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: litetokens
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: litetokens
  wordpress: 
  youtube: 
  google_analytics: UA-21065583-28
  disqus_shortname: 
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next: Next
  str_prev: Prev
  str_continue_reading: Continue reading
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
